### ISSUE TITLE
Increase space between unconnected components

### ISSUE THREAD

**Issue by philipp94831** [bakdata/streams-explorer#101]
It is quite hard to identify connected components in the overall view because nodes are equidistantly placed

**Comment by disrupted** [comment]
Changing Graphviz's ranksep and/or nodesep through `settings.graph_layout_arguments` unfortunately doesn't help in this case as it controls the spacing between all nodes. What we would need is a way of configuring the margin around clusters (our pipeline subgraphs). Without hacks there doesn't seem to be a solution for this at the moment unfortunately.

**Comment by VictorKuenstler** [comment]
Couldn't you calculate every connected component/pipeline layout independently and merge them afterward by updating the y values by an offset?
