### ISSUE TITLE
Move graph layout calculation to frontend

### ISSUE THREAD

**Issue by VictorKuenstler** [bakdata/streams-explorer#104]
Possible relevant use cases:
- Users could have full control over graph layout configurations
- Grouping nodes into separate (sub-)pipelines could be done using [combo groups of G6](https://g6.antv.vision/en/docs/manual/middle/elements/combos/defaultCombo)
- Grouping/filtering nodes can be achieved while providing a useful graph layout
- Updates (new nodes e.g., connectors, streams apps, topics, ...) could be handled without a whole graph reload
- E.g., in the future, Kafka streams app nodes could be expanded to display internal topologies as part of the whole data pipeline

**Comment by disrupted** [comment]
I have been testing it.
- For now the calculated Graph layout from G6 (using Dagre algorithm) looks less robust and structured than what NetworkX currently provides. Perhaps we could re-visit this in a future update of G6.
- Combo groups unfortunately don't seem to have an effect on de-cluttering the graph with multiple connected pipelines.

Will be putting this on hold for now.
