### ISSUE TITLE
Display Kafka topic configs

### ISSUE THREAD

**Issue by VictorKuenstler** [bakdata/streams-explorer#109]
Kafka topic configs such as `compact`/ `delete` in the context of whole pipelines can help to find errors/improvements.

**Comment by disrupted** [comment]
For retrieving the topic configs we can use the `AdminClient` from confluent-kafka:

https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#confluent_kafka.admin.AdminClient.describe_configs
