### ISSUE TITLE
Embed grafana dashboards

### ISSUE THREAD

**Issue by VictorKuenstler** [bakdata/streams-explorer#169]
Grafana supports embedding dashboards in other applications. We could think about embedding some of our dashboards in the node details view. I think the Models UI for KFServing uses Grafana for monitoring similarly:
https://www.kubeflow.org/docs/components/kfserving/webapp/

**Comment by disrupted** [comment]
we discussed this internally and decided against embedding Grafana views. Since there are already links to Grafana we don't want to add more complexity to the frontend.
