### ISSUE TITLE
Streams Application not recognized

### ISSUE THREAD

**Issue by raminqaf** [bakdata/streams-explorer#210]
Currently, when the streams application name is identical to its output topic, the stream explorer fails to recognize the streams application and instead uses the output topic as the application.
The streams explorer should separate the app from the topics even when the App name is equal to its output topic.

**Comment by disrupted** [comment]
We've been discussing this internally.
This is actually an important part of the core design. All graph nodes are required to have a unique identifier, therefore applications and topics should have different names to begin with. This is determined by the `K8sConfigParser.get_id()` method.

Moreover, it is possible to use duplicate names in the visualization, e.g. same name for a streams app and its output topic. It can be desirable to hide internal complexity like pipeline name, prefixes, or suffixes. For this, the `K8sConfigParser.get_name()` method can be customized through the extensible plugin system.
