### ISSUE TITLE
Sink connectors show data flow to dead letter topics although 0 messages written per second

### ISSUE THREAD

**Issue by philipp94831** [bakdata/streams-explorer#218]
If a dead letter topic has 0 messages in per second, the outgoing animated edges of the connector should only go to its target, not the dead letter topic

**Comment by disrupted** [comment]
I am failing to reproduce this issue.

In the below screenshot the visualization is correct
<img width="819" alt="test" src="https://user-images.githubusercontent.com/4771462/213155619-73093d6e-4ee2-47b9-8b6e-adde06d42005.png">
