### ISSUE TITLE
Run on docker

### ISSUE THREAD

**Issue by myrulezzz** [bakdata/streams-explorer#284]
Can i start this image without kubernetes cluster?

**Comment by myrulezzz** [comment]
I get this error when i try to start it with docker-compose File "/app/./streams_explorer/core/services/kubernetes.py", line 72, in setup
    raise Exception("Could not load K8s environment configuration") from e
Exception: Could not load K8s environment configuration

**Comment by disrupted** [comment]
Hi there, thanks for your interest in our project.
Running Streams Explorer outside of Kubernetes is possible using Docker compose, however it still requires a connection to a Kubernetes cluster. Streaming apps are scraped as Kubernetes resources (such as deployments, stateful sets, or cron jobs). This is a fundamental part of the Streams Explorer design.

In addition to the location of the kubeconfig file (see default config in https://github.com/bakdata/streams-explorer/blob/c49e34904a0221b95c63048ec9ee4e33ca73cf15/docker-compose.yaml) you might need to configure the Kubernetes context and namespaces as well.
```yaml
environment:
      ...
      - SE_K8S__deployment__context=your-kubernetes-cluster
      - SE_K8S__deployment__namespaces=['namespace1', 'namespace2']
```
