### ISSUE TITLE
Add support for JDBC Sink Connector 

### ISSUE THREAD

**Issue by philipp94831** [bakdata/streams-explorer#29]
https://docs.confluent.io/kafka-connect-jdbc/current/sink-connector/sink_config_options.html#sink-config-options

**Comment by disrupted** [comment]
@philipp94831 does this database icon fit? https://github.com/bakdata/streams-explorer/blob/e0fec2de95ce06f271e58d891d73ca3b0672191a/frontend/public/jdbc-sink.svg

**Comment by disrupted** [comment]
and do you have an example config for this connector I could test it with?
