### ISSUE TITLE
Search and focus nodes

### ISSUE THREAD

**Issue by VictorKuenstler** [bakdata/streams-explorer#53]
To find nodes easily, a search over all nodes, which allows to select and focus nodes, could enhance usability.

**Comment by disrupted** [comment]
[`graph.focusItem`](https://github.com/antvis/G6/blob/fbd5c02946818918b45d62c1b6168a05c523996a/packages/core/src/graph/graph.ts#L700) centres view on Node, can't zoom in
[`graph.zoomTo`](https://github.com/antvis/G6/blob/fbd5c02946818918b45d62c1b6168a05c523996a/packages/core/src/graph/graph.ts#L689) set zoom level, no animation
