### ISSUE TITLE
Clean Docker image

### ISSUE THREAD

**Issue by disrupted** [bakdata/streams-explorer#64]
Some issues I noticed with the current Docker image

- [x] something is installing Python 2.7
- [x] why are we overwriting uvicorn / fastapi from the base image by installing from `requirements.txt`
- [x] Clean up unneeded packages after build

**Comment by disrupted** [comment]
Update on Python 2.7:
I checked the Debian package dependencies recursively using `apt-cache rdepends package` and I don't see what requires the python2.7-minimal package
Could be Node that installs it ?

**Comment by disrupted** [comment]
About 2) I need @VictorKuenstler's opinion before I change anything 😉

**Comment by VictorKuenstler** [comment]
> About 2) I need @VictorKuenstler's opinion before I change anything 😉
> why are we overwriting uvicorn / fastapi from the base image by installing from requirements.txt

Good point; there is no reason for that. Feel free to optimize this :)
